name: facerecognitiondtr
description: A new Flutter project for Face Recognition DTR.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  dio: ^5.3.3
  camera: ^0.10.5+2
  google_mlkit_face_detection: ^0.11.0
  image: ^4.1.3
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
